version: '3.1'

services:

  mongo_tui:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: test
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - ~/data:/data/db
    networks:
      - app-tier
  redis_tui:
    image: 'redis'
    restart: "always"
    ports:
      - 6379:6379
    networks:
      - app-tier
    volumes:
      - ~/data-redis:/bitname/redis/data
  back_tui:
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-tier
  swager_tui:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    volumes:
      - ./src:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.json
networks:
  app-tier:
    driver: bridge



