version: '3.1'

services:

  mongo_tui:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: test
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - ~/data:/data/db
    networks:
      - app-tier
  redis_tui:
    image: 'redis:alpine'
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge



